# Generated by Django 4.1 on 2022-09-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profilemodel_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='use_remover',
            field=models.BigIntegerField(default=0),
        ),
    ]
