# Generated by Django 4.1 on 2022-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(default=None, upload_to='images/upload/')),
                ('output_image', models.CharField(default='', max_length=500)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
