# Generated by Django 4.1 on 2022-09-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_remover', '0003_alter_imagemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='user',
        ),
    ]
