# Generated by Django 4.1 on 2022-09-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_remover', '0004_remove_imagemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='user',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
