# Generated by Django 4.1 on 2022-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_remover', '0005_imagemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
